workflows:
  menuboss-dev-en-android:
    name: Android Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: 3.10.6
      # 기타 환경 설정
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - name: List directory contents
        script: |
          echo "Listing contents of /Users/builder/clone:"
          ls -al
      - name: Move to menuboss-en directory and check
        script: |
          cd menuboss-en || { echo "Failed to change directory"; exit 1; }
          echo "Changed to directory:"
          pwd
      - name: Move to menuboss-en directory using absolute path
        script: |
          cd /path/to/menuboss-en
          echo "Changed to directory:"
          pwd
      - name: Clean Run Build
        script: make run-rebuild
      - name: Build APK
        script: make create-apk-dev
    artifacts:
      - build/**/outputs/**/*.apk

  menuboss-dev-en-ios:
    name: iOS Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: 3.10.6
      xcode: 14.3.1
      # 기타 환경 설정
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - name: Move to menuboss-en directory
        script: cd menuboss-en
      - name: Clean Run Build
        script: make run-rebuild
    artifacts:
      - build/ios/ipa/*.ipa