// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiCJc6FfE9BGx38TIkvs8bQBTPaFtL3a0',
    appId: '1:922858947237:android:efbd03ca1d9fb9f683434c',
    messagingSenderId: '922858947237',
    projectId: 'menuboss-app-dev',
    storageBucket: 'menuboss-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuf8vxwnlpLpqiSx1C-XaXb-LL9Bg68oQ',
    appId: '1:922858947237:ios:abd000816b5f49bb83434c',
    messagingSenderId: '922858947237',
    projectId: 'menuboss-app-dev',
    storageBucket: 'menuboss-app-dev.appspot.com',
    androidClientId: '922858947237-qti9p87mlmqg195iqeqae73egnq8ok8e.apps.googleusercontent.com',
    iosClientId: '922858947237-5l6poa73hhachqdijn2k59h1v2rb7r7b.apps.googleusercontent.com',
    iosBundleId: 'com.orot.menuboss.kr.dev',
  );
}
